loomio_webhooks:
  repo:         pqrkchqps/loomio_webhooks

loomio_org_plugin:
  repo:         pqrkchqps/loomio_org_plugin

loomio_tags:
  repo:         pqrkchqps/loomio_tags

loomio_truncate_comment:
  repo:         pqrkchqps/loomio_truncate_comment
  experimental: true

loomio_content_preview:
  repo:         pqrkchqps/loomio_content_preview

loomio_buyer_experience:
  repo:         pqrkchqps/loomio_buyer_experience

loomio_onboarding:
  repo:         pqrkchqps/loomio_onboarding
  branch:       group-form-update
