diehard_fund_webhooks:
  repo:         diehard_fund/diehard_fund_webhooks

diehard_fund_org_plugin:
  repo:         diehard_fund/diehard_fund_org_plugin

diehard_fund_tags:
  repo:         diehard_fund/diehard_fund_tags

diehard_fund_truncate_comment:
  repo:         diehard_fund/diehard_fund_truncate_comment
  experimental: true

diehard_fund_content_preview:
  repo:         diehard_fund/diehard_fund_content_preview

diehard_fund_buyer_experience:
  repo:         diehard_fund/diehard_fund_buyer_experience

diehard_fund_onboarding:
  repo:         diehard_fund/diehard_fund_onboarding
  branch:       group-form-update
