diehard-dot-fund_webhooks:
  repo:         pqrkchqps/diehard-dot-fund_webhooks

diehard-dot-fund_org_plugin:
  repo:         pqrkchqps/diehard-dot-fund_org_plugin

diehard-dot-fund_tags:
  repo:         pqrkchqps/diehard-dot-fund_tags

diehard-dot-fund_truncate_comment:
  repo:         pqrkchqps/diehard-dot-fund_truncate_comment

diehard-dot-fund_content_preview:
  repo:         pqrkchqps/diehard-dot-fund_content_preview

diehard-dot-fund_buyer_experience:
  repo:         pqrkchqps/diehard-dot-fund_buyer_experience

diehard-dot-fund_onboarding:
  repo:         pqrkchqps/diehard-dot-fund_onboarding
  branch:       group-form-update
