diehard-dot-fund_webhooks:
  repo:         https://github.com/pqrkchqps/diehard-dot-fund_webhooks.git

diehard-dot-fund_org_plugin:
  repo:         https://github.com/pqrkchqps/diehard-dot-fund_org_plugin.git

diehard-dot-fund_tags:
  repo:         https://github.com/pqrkchqps/diehard-dot-fund_tags.git

diehard-dot-fund_truncate_comment:
  repo:         https://github.com/pqrkchqps/diehard-dot-fund_truncate_comment.git

diehard-dot-fund_content_preview:
  repo:         https://github.com/pqrkchqps/diehard-dot-fund_content_preview.git

diehard-dot-fund_onboarding:
  repo:         https://github.com/pqrkchqps/diehard-dot-fund_onboarding.git
